Remove Old JWT Tables
microsoft/CCF pull request #6302
Opened 2024-06-27 21:16 UTC by sidmore

2024-06-28 08:28 UTC, achamayou commented on samples/constitutions/default/actions.js
> +          args !== undefined &&
The first comparison should be sufficient to mandate that args is undefined.

2024-06-28 08:34 UTC, achamayou commented
@maxtropets please review.

@sidmore because this change requires user-action, can you add an entry in the CHANGELOG to describe it? There seems to be an OpenAPI change (not immediately clear why), so please run the schema test locally and diff the schemas. If the change is expected, updating the OpenAPI version in the governance frontend file, rebuilding, re-running the test and checking in the schema is the way to go. If the change is unexpected, let's discuss.

2024-06-28 08:54 UTC, eddyashton commented on samples/constitutions/default/actions.js
> +        }
We have a helper function that does this already - best to use that for a consistent error message.

```suggestion
        checkNone(args);
```

2024-06-28 08:57 UTC, eddyashton commented on tests/infra/consortium.py
> +    def remove_old_jwt_tables(self, remote_node, issuer):
Looks like we're not actually calling this anywhere. We should add a call to this in the `lts_compatibility` test (or one of the tests in `recovery.py` that recovers from an old ledger), to fully confirm that we can have a service where these tables are present _before_ the call, removed _after_ the call, and not repopulated if we do a jwt refresh.

2024-06-28 12:55 UTC, maxtropets commented
We also probably shall prepare some template for operators (not sure where to put it though, probably @achamayou could elaborate on our vision here), 
 
The goal is to have an ultimate step-by-step guide for how to upgrade, probably introduce some scripts to automate some work. I'm not really sure what's the average operator expertise level is.

2024-07-02 16:22 UTC, sidmore commented
> @maxtropets please review.
> 
> @sidmore because this change requires user-action, can you add an entry in the CHANGELOG to describe it? There seems to be an OpenAPI change (not immediately clear why), so please run the schema test locally and diff the schemas. If the change is expected, updating the OpenAPI version in the governance frontend file, rebuilding, re-running the test and checking in the schema is the way to go. If the change is unexpected, let's discuss.

@achamayou i have updated the schema for gov

2024-07-09 14:57 UTC, maxtropets requested changes

2024-07-12 15:45 UTC, sidmore commented on samples/constitutions/default/actions.js
> +
add a trigger snapshot action

2024-07-12 15:48 UTC, sidmore commented on tests/recovery.py
> +
stop the network here to trigger a flush to disk

2024-10-16 13:27 UTC, achamayou commented
@sidmore now that `release/5.x` is cut, it'd be great to update this and get it merged.

2025-02-12 17:45 UTC, closed without merging

2025-02-12 17:45 UTC, achamayou commented
We aren't going to have the time to complete this by 6.0.0-rc0, and because of the multi-IdP support changes, there are additional tables we need to clean up too. This is tracked in #6222, and can start as soon as we have cut `release/6.x`, and until `7.0.0-rc0` at the latest.

This PR is cross-linked and can be used as a starting point when we schedule this work.